plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.139'
}

tasks.named('wrapper', Wrapper).configure {
    // 在这里定义包装器值，以便在更新 gradlew.properties 时不必总是这样做。
    // 将其切换为 Wrapper.DistributionType.ALL 将下载附带的完整 gradle 源
    // 光标悬停在 gradle 类和方法上的附加文档。然而，这伴随着增加
    // Gradle 的文件大小。如果您确实将其切换为 ALL，请随后运行 Gradle 包装器任务两次。
    // （通过检查 gradle/wrapper/gradle-wrapper.properties 来验证 distributionUrl 现在是否指向 `-all`）
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_name
}

// Mojang ships Java 17 to end users in 1.20.1, so mods should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    // Specify the version of MinecraftForge to use.
    version = project.minecraft_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            //programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        // 此运行配置启动 GameTestServer 并运行所有已注册的游戏测试，然后退出。
        // 默认情况下，如果没有提供游戏测试，服务器将会崩溃。
        // 对于 /test 命令下的其他运行配置，默认情况下也会启用游戏测试系统。
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            jvmArguments.add "-XX:+AllowEnhancedClassRedefinition"
            jvmArguments.add "-XX:HotswapAgent=fatjar"
            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // 定义 mod <-> 源绑定
        // 这些用于告诉游戏哪些来源适用于哪个模组
        // 在单个 mod 项目中大部分是可选的
        // 但多 mod 项目应该为每个 mod 定义一个
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

// 包括数据生成器生成的资源。
sourceSets.main.resources { srcDir 'src/generated/resources' }

// 设置一个名为“localRuntime”的依赖配置和一个名为“modLocalRuntime”的反混淆配置
// 这些配置应该使用而不是'runtimeOnly'来声明
// 将存在用于运行时测试的依赖项，但那是
// “可选”，意味着它不会被该 mod 的依赖者拉动。
configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}
repositories {
    maven {
        url 'https://cursemaven.com'
    }
    flatDir {
        dir 'libs'
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:24.0.1'
    modCompileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.2.0-rc.2"))
    jarJar(modImplementation("io.github.llamalad7:mixinextras-forge:0.2.0-rc.2"))

    modImplementation("curse.maven:jei-238222:6600311")
    modImplementation("curse.maven:mutil-351914:6418901")
    modImplementation("curse.maven:tetra-289712:6418957")
    modCompileOnly("curse.maven:extraholopage-1301292:7021781")

    modRuntimeOnly("blank:IBEEditor-1.20:2.2.8-forge")
    modRuntimeOnly("blank:ModernUI-Forge:1.20.1-3.11.1.6-universal")


    //1.8.60
    //modImplementation("curse.maven:slashblade-resharped-1022428:7194599")
    //1.9.65
    modImplementation("curse.maven:slashblade-resharped-1022428:8090912")

    modImplementation("curse.maven:mysterious-mountain-lib-368098:6955193")
    modImplementation("curse.maven:slashblade-hf-blade-1299888:6917439")
    modImplementation("curse.maven:the-last-smith-306385:6982449")
}

// Uncomment the lines below if you wish to configure mixin. The mixin file should be named modid.mixins.json.

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
}

jar {
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}


// 此代码块扩展指定资源目标中所有声明的替换属性。
// 缺少属性将导致错误。属性使用 ${} Groovy 表示法进行扩展。
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// 包含“generateModMetadata”的输出作为构建的输入目录
// 这适用于通过 Gradle 和 IDE 构建.
sourceSets.main.resources.srcDir generateModMetadata
// 为了避免手动运行“generateModMetadata”，请使其在每次项目重新加载时运行
legacyForge.ideSyncTask generateModMetadata

// 允许使用 maven-publish 插件进行发布的示例配置
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
